// This file has been generated by the dart_json_mapper v2.2.9
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'models/app_error.dart' as x1 show AppError;
import 'models/app_model.dart' as x3 show TodoFilter;
import 'models/auth.dart' as x0 show Jwt, Credentials;
import 'models/todo.dart' as x2 show Todo, UserTodo;
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show
        JsonMapper,
        JsonMapperAdapter,
        SerializationOptions,
        DeserializationOptions,
        typeOf;
// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:todomvc/models/app_error.dart' as prefix3;
import 'package:todomvc/models/auth.dart' as prefix2;
import 'package:todomvc/models/todo.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'Todo',
            r'.Todo',
            134217735,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 3, 4, 20, 21],
            const <int>[
              22,
              23,
              24,
              25,
              26,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19
            ],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({task, due, done = false, doneAt, id}) => b
                  ? prefix1.Todo(
                      done: done, doneAt: doneAt, due: due, id: id, task: task)
                  : null,
              r'fromMap': (bool b) => (m) => b ? prefix1.Todo.fromMap(m) : null
            },
            -1,
            0,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'UserTodo',
            r'.UserTodo',
            134217735,
            1,
            const prefix0.JsonSerializable(),
            const <int>[5, 29],
            const <int>[
              22,
              23,
              24,
              25,
              26,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              27,
              28
            ],
            const <int>[],
            0,
            {},
            {},
            {
              r'': (bool b) =>
                  (token, t) => b ? prefix1.UserTodo(token, t) : null
            },
            -1,
            1,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'Jwt',
            r'.Jwt',
            134217735,
            2,
            const prefix0.JsonSerializable(),
            const <int>[6, 31],
            const <int>[22, 23, 24, 25, 26, 30],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => (token) => b ? prefix2.Jwt(token) : null},
            -1,
            2,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'Credentials',
            r'.Credentials',
            134217735,
            3,
            const prefix0.JsonSerializable(),
            const <int>[7, 8, 36],
            const <int>[22, 23, 24, 25, 26, 32, 33, 34, 35],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix2.Credentials() : null},
            -1,
            3,
            const <int>[],
            const [prefix0.jsonSerializable],
            null),
        r.NonGenericClassMirrorImpl(
            r'AppError',
            r'.AppError',
            134217735,
            4,
            const prefix0.JsonSerializable(),
            const <int>[9, 38, 39, 40],
            const <int>[22, 23, 24, 25, 26, 37, 38],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  (message) => b ? prefix3.AppError(message) : null,
              r'empty': (bool b) => () => b ? prefix3.AppError.empty() : null
            },
            -1,
            4,
            const <int>[],
            const [prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'task',
            134348805,
            0,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'due',
            134348805,
            0,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6, const <int>[], const []),
        r.VariableMirrorImpl(
            r'done',
            134348805,
            0,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7, const <int>[], const []),
        r.VariableMirrorImpl(
            r'doneAt',
            67239941,
            0,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [const prefix0.JsonProperty(ignoreIfNull: true)]),
        r.VariableMirrorImpl(
            r'id',
            67239941,
            0,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [const prefix0.JsonProperty(ignoreIfNull: true)]),
        r.VariableMirrorImpl(
            r'token',
            134348805,
            1,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'token',
            134349829,
            2,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'email',
            134348805,
            3,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'pass',
            134348805,
            3,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.VariableMirrorImpl(
            r'message',
            134349829,
            4,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 10),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 11),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 12),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 13),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 14),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 2, 15),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 16),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 3, 17),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 4, 18),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 4, 19),
        r.MethodMirrorImpl(
            r'',
            0,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[0, 1, 2, 3, 4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'fromMap', 0, 0, -1, 0, 0, const <int>[],
            const <int>[5], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 7, 7, const <int>[],
            const <int>[11], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[12],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 10, 10, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            2097155,
            -1,
            -1,
            11,
            11,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 5, 27),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 5, 28),
        r.MethodMirrorImpl(r'', 0, 1, -1, 1, 1, const <int>[],
            const <int>[13, 14], const prefix0.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 6, 30),
        r.MethodMirrorImpl(r'', 0, 2, -1, 2, 2, const <int>[], const <int>[16],
            const prefix0.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 7, 32),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 7, 33),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 8, 34),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 8, 35),
        r.MethodMirrorImpl(r'', 0, 3, -1, 3, 3, const <int>[], const <int>[],
            const prefix0.JsonSerializable(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 9, 37),
        r.MethodMirrorImpl(r'isEmpty', 2097155, 4, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'', 0, 4, -1, 4, 4, const <int>[], const <int>[19],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'empty', 0, 4, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'task',
            134358022,
            20,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            #task),
        r.ParameterMirrorImpl(
            r'due',
            67252230,
            20,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            #due),
        r.ParameterMirrorImpl(
            r'done',
            134364166,
            20,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            false,
            #done),
        r.ParameterMirrorImpl(
            r'doneAt',
            67252230,
            20,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            #doneAt),
        r.ParameterMirrorImpl(
            r'id',
            67253254,
            20,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'm',
            151126022,
            21,
            const prefix0.JsonSerializable(),
            -1,
            12,
            13,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_task',
            134348902,
            11,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_due',
            134348902,
            13,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_done',
            134348902,
            15,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_doneAt',
            67240038,
            17,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_id',
            67240038,
            19,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            22,
            const prefix0.JsonSerializable(),
            -1,
            14,
            14,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            24,
            const prefix0.JsonSerializable(),
            -1,
            15,
            15,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'token',
            134349830,
            29,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r't',
            134348806,
            29,
            const prefix0.JsonSerializable(),
            0,
            0,
            0,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_token',
            134348902,
            28,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'token',
            134349830,
            31,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_email',
            134348902,
            33,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_pass',
            134348902,
            35,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'message',
            67239942,
            39,
            const prefix0.JsonSerializable(),
            -1,
            16,
            16,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.Todo,
        prefix1.UserTodo,
        prefix2.Jwt,
        prefix2.Credentials,
        prefix3.AppError,
        String,
        DateTime,
        bool,
        DateTime,
        int,
        int,
        Type,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        Object,
        Invocation,
        String
      ],
      5,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'task': (dynamic instance) => instance.task,
        r'due': (dynamic instance) => instance.due,
        r'done': (dynamic instance) => instance.done,
        r'doneAt': (dynamic instance) => instance.doneAt,
        r'id': (dynamic instance) => instance.id,
        r'token': (dynamic instance) => instance.token,
        r'email': (dynamic instance) => instance.email,
        r'pass': (dynamic instance) => instance.pass,
        r'message': (dynamic instance) => instance.message,
        r'isEmpty': (dynamic instance) => instance.isEmpty
      },
      {
        r'task=': (dynamic instance, value) => instance.task = value,
        r'due=': (dynamic instance, value) => instance.due = value,
        r'done=': (dynamic instance, value) => instance.done = value,
        r'doneAt=': (dynamic instance, value) => instance.doneAt = value,
        r'id=': (dynamic instance, value) => instance.id = value,
        r'token=': (dynamic instance, value) => instance.token = value,
        r'email=': (dynamic instance, value) => instance.email = value,
        r'pass=': (dynamic instance, value) => instance.pass = value
      },
      null,
      [])
};

const _memberSymbolMap = null;

void _initializeReflectable(JsonMapperAdapter adapter) {
  if (!adapter.isGenerated) {
    return;
  }
  r.data = adapter.reflectableData!;
  r.memberSymbolMap = adapter.memberSymbolMap;
}

final mainGeneratedAdapter = JsonMapperAdapter(
    title: 'todomvc',
    url: 'package:todomvc/main.dart',
    reflectableData: _data,
    memberSymbolMap: _memberSymbolMap,
    valueDecorators: {
      typeOf<List<x0.Jwt>>(): (value) => value.cast<x0.Jwt>(),
      typeOf<Set<x0.Jwt>>(): (value) => value.cast<x0.Jwt>(),
      typeOf<List<x0.Credentials>>(): (value) => value.cast<x0.Credentials>(),
      typeOf<Set<x0.Credentials>>(): (value) => value.cast<x0.Credentials>(),
      typeOf<List<x1.AppError>>(): (value) => value.cast<x1.AppError>(),
      typeOf<Set<x1.AppError>>(): (value) => value.cast<x1.AppError>(),
      typeOf<List<x2.Todo>>(): (value) => value.cast<x2.Todo>(),
      typeOf<Set<x2.Todo>>(): (value) => value.cast<x2.Todo>(),
      typeOf<List<x2.UserTodo>>(): (value) => value.cast<x2.UserTodo>(),
      typeOf<Set<x2.UserTodo>>(): (value) => value.cast<x2.UserTodo>(),
      typeOf<List<x3.TodoFilter>>(): (value) => value.cast<x3.TodoFilter>(),
      typeOf<Set<x3.TodoFilter>>(): (value) => value.cast<x3.TodoFilter>()
    },
    enumValues: {
      x3.TodoFilter: x3.TodoFilter.values
    });

Future<JsonMapper> initializeJsonMapperAsync(
        {Iterable<JsonMapperAdapter> adapters = const [],
        SerializationOptions? serializationOptions,
        DeserializationOptions? deserializationOptions}) =>
    Future(() => initializeJsonMapper(
        adapters: adapters,
        serializationOptions: serializationOptions,
        deserializationOptions: deserializationOptions));

JsonMapper initializeJsonMapper(
    {Iterable<JsonMapperAdapter> adapters = const [],
    SerializationOptions? serializationOptions,
    DeserializationOptions? deserializationOptions}) {
  JsonMapper.globalSerializationOptions =
      serializationOptions ?? JsonMapper.globalSerializationOptions;
  JsonMapper.globalDeserializationOptions =
      deserializationOptions ?? JsonMapper.globalDeserializationOptions;
  JsonMapper.enumerateAdapters([...adapters, mainGeneratedAdapter],
      (JsonMapperAdapter adapter) {
    _initializeReflectable(adapter);
    JsonMapper().useAdapter(adapter);
  });
  return JsonMapper();
}
