### Executable with VSCode REST Client extension

### When testing routes which require Authorization header
### execute /rpc/login first, then copy returned JWT token into
### respective request


### Auth, return token
POST http://localhost:3000/rpc/login HTTP/1.1
Content-Type: application/json
Content-Profile: app_auth
Accept: application/vnd.pgrst.object+json

{
    "email": "john.doe@lost.net",
    "pass": "johnny88"
}

### Auth, failure
POST http://localhost:3000/rpc/login HTTP/1.1
Content-Type: application/json
Content-Profile: app_auth
Accept: application/vnd.pgrst.object+json

{
    "email": "unknown@lost.net",
    "pass": "dummy"
}

### Todo-s, over all users
GET http://localhost:3000/todos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYXBwdXNlciIsImVtYWlsIjoiam9obi5kb2VAbG9zdC5uZXQiLCJ1aWQiOjEsImV4cCI6MTYwNjY1Mzk1NH0.wb_afspPRUZWD1IeYO_SU8vJXhuP8Irwpkzm0lGn1GQ

### Todo-s, for user 2 via id
GET http://localhost:3000/todos?user_id=eq.2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYXBwdXNlciIsImVtYWlsIjoiam9obi5kb2VAbG9zdC5uZXQiLCJ1aWQiOjEsImV4cCI6MTYwNjY1Mzk1NH0.wb_afspPRUZWD1IeYO_SU8vJXhuP8Irwpkzm0lGn1GQ

### Todo-s, restricted through token
POST http://localhost:3000/rpc/user_todos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYXBwdXNlciIsImVtYWlsIjoiam9obi5kb2VAbG9zdC5uZXQiLCJ1aWQiOjEsImV4cCI6MTYwNjY1Mzk1NH0.wb_afspPRUZWD1IeYO_SU8vJXhuP8Irwpkzm0lGn1GQ
Prefer: params=single-object

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYXBwdXNlciIsImVtYWlsIjoiam9obi5kb2VAbG9zdC5uZXQiLCJ1aWQiOjEsImV4cCI6MTYwNjY1Mzk1NH0.wb_afspPRUZWD1IeYO_SU8vJXhuP8Irwpkzm0lGn1GQ"}

### New Todo, for user 1
POST http://localhost:3000/todos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYXBwdXNlciIsImVtYWlsIjoiam9obi5kb2VAbG9zdC5uZXQiLCJ1aWQiOjEsImV4cCI6MTYwNjY1Mzk1NH0.wb_afspPRUZWD1IeYO_SU8vJXhuP8Irwpkzm0lGn1GQ

{
  "user_id": 1,
  "task": "Buy cookies with milk"
}

### Update Todo, for user 1
PATCH http://localhost:3000/todos?id=eq.4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYXBwdXNlciIsImVtYWlsIjoiam9obi5kb2VAbG9zdC5uZXQiLCJ1aWQiOjEsImV4cCI6MTYwNjY1Mzk1NH0.wb_afspPRUZWD1IeYO_SU8vJXhuP8Irwpkzm0lGn1GQ

{
  "done": true
}
